export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE'

export const LOAD_PUBLISH_POSTS_REQUEST = 'LOAD_PUBLISH_POSTS_REQUEST'
export const LOAD_PUBLISH_POSTS_SUCCESS = 'LOAD_PUBLISH_POSTS_SUCCESS'
export const LOAD_PUBLISH_POSTS_FAILURE = 'LOAD_PUBLISH_POSTS_FAILURE'

export const LOAD_POSTS_BY_USER_REQUEST = 'LOAD_POSTS_BY_USER_REQUEST'
export const LOAD_POSTS_BY_USER_SUCCESS = 'LOAD_POSTS_BY_USER_SUCCESS'
export const LOAD_POSTS_BY_USER_FAILURE = 'LOAD_POSTS_BY_USER_FAILURE'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILURE = 'AUTH_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
